spring.datasource.url = jdbc:mysql://${MYSQL_HOSTNAME:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:ai_news}
spring.datasource.username= ${MYSQL_USERNAME:root}
spring.datasource.password= ${MYSQL_PASSWORD:mysql1234}
spring.h2.console.enabled=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto= update
spring.jpa.database= mysql

# bing
news.api.key=${BING_API_KEY:41e1e1c86fb14e87a2a9f96342338744}

#qwen
qwen.api.key=${QWEN_API_KEY:sk-6570a4b76ddd41d383191701c68aecf5}

#Youtube
youtube.api.key=${YOUTUBE_API_KEY:AIzaSyDXs99RBMlc94sLL-scWqUX4_qMc9b8eh4}
