spring.datasource.url = jdbc:mysql://${MYSQL_HOSTNAME:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:amealia}
spring.datasource.username= ${MYSQL_USERNAME:root}
spring.datasource.password= ${MYSQL_PASSWORD:mysql1234}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# JPA/Hibernate
spring.jpa.hibernate.ddl-auto= update
spring.jpa.database= mysql
